# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\LBT项目\LBT\UI\Add.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogAdd(object):
    def setupUi(self, DialogAdd):
        DialogAdd.setObjectName("DialogAdd")
        DialogAdd.resize(518, 508)
        DialogAdd.setSizeGripEnabled(True)
        self.comboBoxChipSelect = QtWidgets.QComboBox(DialogAdd)
        self.comboBoxChipSelect.setGeometry(QtCore.QRect(90, 40, 69, 22))
        self.comboBoxChipSelect.setObjectName("comboBoxChipSelect")
        self.comboBoxChipSelect.addItem("")
        self.comboBoxChipSelect.addItem("")
        self.comboBoxChipSelect.addItem("")
        self.comboBoxChipSelect.addItem("")
        self.comboBoxChipSelect.addItem("")
        self.gridLayoutWidget = QtWidgets.QWidget(DialogAdd)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 100, 179, 106))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutModuleSelect = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutModuleSelect.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutModuleSelect.setObjectName("gridLayoutModuleSelect")
        self.radioButtonUART = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonUART.setObjectName("radioButtonUART")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonUART, 3, 1, 1, 1)
        self.radioButtonLCD = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonLCD.setObjectName("radioButtonLCD")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonLCD, 3, 0, 1, 1)
        self.radioButtonSPI = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonSPI.setObjectName("radioButtonSPI")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonSPI, 2, 0, 1, 1)
        self.radioButtonDCMI = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonDCMI.setObjectName("radioButtonDCMI")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonDCMI, 1, 1, 1, 1)
        self.radioButtonPWM = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonPWM.setObjectName("radioButtonPWM")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonPWM, 1, 2, 1, 1)
        self.radioButtonMIPI = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonMIPI.setObjectName("radioButtonMIPI")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonMIPI, 2, 1, 1, 1)
        self.radioButtonKeyBoard = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonKeyBoard.setObjectName("radioButtonKeyBoard")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonKeyBoard, 3, 2, 1, 1)
        self.radioButtonSCI = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonSCI.setObjectName("radioButtonSCI")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonSCI, 1, 0, 1, 1)
        self.radioButtonI2C = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonI2C.setObjectName("radioButtonI2C")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonI2C, 4, 0, 1, 1)
        self.radioButtonSDIO = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonSDIO.setObjectName("radioButtonSDIO")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonSDIO, 4, 1, 1, 1)
        self.radioButtonSDRAM = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonSDRAM.setObjectName("radioButtonSDRAM")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonSDRAM, 4, 2, 1, 1)
        self.radioButtonADC = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonADC.setObjectName("radioButtonADC")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonADC, 5, 0, 1, 1)
        self.radioButtonPSRAM = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButtonPSRAM.setObjectName("radioButtonPSRAM")
        self.gridLayoutModuleSelect.addWidget(self.radioButtonPSRAM, 2, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(DialogAdd)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 230, 91, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayoutIOInput = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutIOInput.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutIOInput.setObjectName("verticalLayoutIOInput")
        self.horizontalLayoutModuleInput = QtWidgets.QHBoxLayout()
        self.horizontalLayoutModuleInput.setObjectName("horizontalLayoutModuleInput")
        self.labelModule = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelModule.setObjectName("labelModule")
        self.horizontalLayoutModuleInput.addWidget(self.labelModule)
        self.lineEditModuleInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditModuleInput.setObjectName("lineEditModuleInput")
        self.horizontalLayoutModuleInput.addWidget(self.lineEditModuleInput)
        self.verticalLayoutIOInput.addLayout(self.horizontalLayoutModuleInput)
        self.horizontalLayoutGroupInput = QtWidgets.QHBoxLayout()
        self.horizontalLayoutGroupInput.setObjectName("horizontalLayoutGroupInput")
        self.labelGroupInput = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelGroupInput.setObjectName("labelGroupInput")
        self.horizontalLayoutGroupInput.addWidget(self.labelGroupInput)
        self.comboBoxGroupSelect = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxGroupSelect.setObjectName("comboBoxGroupSelect")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.comboBoxGroupSelect.addItem("")
        self.horizontalLayoutGroupInput.addWidget(self.comboBoxGroupSelect)
        self.verticalLayoutIOInput.addLayout(self.horizontalLayoutGroupInput)
        self.horizontalLayoutPinInput = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPinInput.setObjectName("horizontalLayoutPinInput")
        self.labelPinInput = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelPinInput.setObjectName("labelPinInput")
        self.horizontalLayoutPinInput.addWidget(self.labelPinInput)
        self.lineEditPinInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditPinInput.setObjectName("lineEditPinInput")
        self.horizontalLayoutPinInput.addWidget(self.lineEditPinInput)
        self.verticalLayoutIOInput.addLayout(self.horizontalLayoutPinInput)
        self.horizontalLayoutRemapInput = QtWidgets.QHBoxLayout()
        self.horizontalLayoutRemapInput.setObjectName("horizontalLayoutRemapInput")
        self.labelRemapInput = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelRemapInput.setObjectName("labelRemapInput")
        self.horizontalLayoutRemapInput.addWidget(self.labelRemapInput)
        self.comboBoxRemapSelect = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxRemapSelect.setObjectName("comboBoxRemapSelect")
        self.comboBoxRemapSelect.addItem("")
        self.comboBoxRemapSelect.addItem("")
        self.comboBoxRemapSelect.addItem("")
        self.horizontalLayoutRemapInput.addWidget(self.comboBoxRemapSelect)
        self.verticalLayoutIOInput.addLayout(self.horizontalLayoutRemapInput)
        self.pushButton = QtWidgets.QPushButton(DialogAdd)
        self.pushButton.setGeometry(QtCore.QRect(180, 240, 131, 101))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(DialogAdd)
        self.textEdit.setGeometry(QtCore.QRect(40, 410, 281, 71))
        self.textEdit.setObjectName("textEdit")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(DialogAdd)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(300, 80, 160, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayouttest = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayouttest.setContentsMargins(0, 0, 0, 0)
        self.gridLayouttest.setHorizontalSpacing(10)
        self.gridLayouttest.setVerticalSpacing(15)
        self.gridLayouttest.setObjectName("gridLayouttest")

        self.retranslateUi(DialogAdd)
        self.radioButtonUART.clicked.connect(self.textEdit.paste)
        QtCore.QMetaObject.connectSlotsByName(DialogAdd)

    def retranslateUi(self, DialogAdd):
        _translate = QtCore.QCoreApplication.translate
        DialogAdd.setWindowTitle(_translate("DialogAdd", "Dialog"))
        self.comboBoxChipSelect.setItemText(0, _translate("DialogAdd", "MH1901"))
        self.comboBoxChipSelect.setItemText(1, _translate("DialogAdd", "MH1902"))
        self.comboBoxChipSelect.setItemText(2, _translate("DialogAdd", "MH1902S"))
        self.comboBoxChipSelect.setItemText(3, _translate("DialogAdd", "MH1903"))
        self.comboBoxChipSelect.setItemText(4, _translate("DialogAdd", "MH1901H"))
        self.radioButtonUART.setText(_translate("DialogAdd", "UART"))
        self.radioButtonLCD.setText(_translate("DialogAdd", "LCD"))
        self.radioButtonSPI.setText(_translate("DialogAdd", "SPI"))
        self.radioButtonDCMI.setText(_translate("DialogAdd", "DCMI"))
        self.radioButtonPWM.setText(_translate("DialogAdd", "PWM"))
        self.radioButtonMIPI.setText(_translate("DialogAdd", "MIPI"))
        self.radioButtonKeyBoard.setText(_translate("DialogAdd", "KeyBoard"))
        self.radioButtonSCI.setText(_translate("DialogAdd", "SCI"))
        self.radioButtonI2C.setText(_translate("DialogAdd", "I2C"))
        self.radioButtonSDIO.setText(_translate("DialogAdd", "SDIO"))
        self.radioButtonSDRAM.setText(_translate("DialogAdd", "SDRAM"))
        self.radioButtonADC.setText(_translate("DialogAdd", "ADC"))
        self.radioButtonPSRAM.setText(_translate("DialogAdd", "PSRAM"))
        self.labelModule.setText(_translate("DialogAdd", "Module"))
        self.labelGroupInput.setText(_translate("DialogAdd", "Group"))
        self.comboBoxGroupSelect.setItemText(0, _translate("DialogAdd", "A"))
        self.comboBoxGroupSelect.setItemText(1, _translate("DialogAdd", "B"))
        self.comboBoxGroupSelect.setItemText(2, _translate("DialogAdd", "C"))
        self.comboBoxGroupSelect.setItemText(3, _translate("DialogAdd", "D"))
        self.comboBoxGroupSelect.setItemText(4, _translate("DialogAdd", "E"))
        self.comboBoxGroupSelect.setItemText(5, _translate("DialogAdd", "F"))
        self.comboBoxGroupSelect.setItemText(6, _translate("DialogAdd", "G"))
        self.comboBoxGroupSelect.setItemText(7, _translate("DialogAdd", "H"))
        self.labelPinInput.setText(_translate("DialogAdd", "Pin"))
        self.labelRemapInput.setText(_translate("DialogAdd", "Remap"))
        self.comboBoxRemapSelect.setItemText(0, _translate("DialogAdd", "0"))
        self.comboBoxRemapSelect.setItemText(1, _translate("DialogAdd", "2"))
        self.comboBoxRemapSelect.setItemText(2, _translate("DialogAdd", "3"))
        self.pushButton.setText(_translate("DialogAdd", "添加"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAdd = QtWidgets.QDialog()
    ui = Ui_DialogAdd()
    ui.setupUi(DialogAdd)
    DialogAdd.show()
    sys.exit(app.exec_())

